// data.js
const Food_List = [
  {
    id: 1,
    image: "Image/Chicken Tikka.jpg",
    name: "Butter Chicken Combo",
    alias: "Chicken Combo",
    price: 14,
    tags: ["Dairy", "Nuts", "Gluten", "Egg"],
  },
  {
    id: 2,
    image: "Image/Paneer Tikka.jpg",
    name: "Paneer Tikka Masala Combo",
    alias: "Paneer Combo",
    price: 14,
    tags: ["Dairy", "Nuts", "Gluten", "Egg"],
  },
  {
    id: 3,
    image: "Image/Chole.jpg",
    name: "Channa Masala Combo",
    alias: "Channa Combo",
    price: 14,
    tags: ["Vegan", "Gluten", "Egg"],
  },
  {
    id: 4,
    image: "Image/Tandoori.jpg",
    name: "Tandoori Chicken",
    alias: "Tandoori Chicken",
    price: 7,
    tags: ["Dairy"],
  },
  {
    id: 5,
    image: "Image/Samosa.jpg",
    name: "Samosa",
    alias: "Samosa",
    price: 6,
    tags: ["Vegan", "Gluten"],
  },
  {
    id: 6,
    image: "Image/Lassi.jpg",
    name: "Mango Lassi",
    alias: "Mango Lassi",
    price: 6,
    comboPrice: 3,
    tags: ["Dairy", "Cold"],
  },
  {
    id: 7,
    image: "Image/Water.jpg",
    name: "Water",
    alias: "Water",
    price: 2,
    tags: ["Cold"],
  },
  {
    id: 8,
    image: "Image/Soda.jpg",
    name: "Soda",
    alias: "Soda",
    price: 2,
    tags: ["Cold"],
  },
  {
    id: 9,
    image: "Image/Extra.jpg",
    name: "Extra Rice/Naan",
    alias: "Extra Rice/Naan",
    price: 1,
    tags: ["Gluten", "Egg"],
  },
];

export default Food_List;
