// data.js
const Food_List = [
  {
    id: 1,
    image: "/Image/Chicken Tikka.jpg",
    name: "Chicken Butter Masala",
    alias: "Chicken Box",
    price: 12,
    tags: ["Diary", "Nuts", "Gluten", "Egg"],
  },
  {
    id: 2,
    image: "/Image/Paneer Tikka.jpg",
    name: "Panner Tikka Masala",
    alias: "Panner Box",
    price: 12,
    tags: ["Diary", "Nuts", "Gluten", "Egg"],
  },
  {
    id: 3,
    image: "/Image/Chole.jpg",
    name: "Chickpea Masala",
    alias: "Chickpea Box",
    price: 12,
    tags: ["Vegan", "Gluten", "Egg"],
  },
  {
    id: 4,
    image: "/Image/Tandoori.jpg",
    name: "Tandoori Chicken",
    alias: "Tandoori Chicken",
    price: 6,
    tags: ["Diary"],
  },
  {
    id: 5,
    image: "/Image/Extra.jpg",
    name: "Extra Rice/Naan",
    alias: "Extra Rice/Naan",
    price: 1,
    tags: ["Gluten", "Egg"],
  },
  {
    id: 6,
    image: "/Image/Chicken Tikka.jpg",
    name: "Chicken Butter Masala Combo",
    alias: "Chicken Combo",
    price: 15,
    tags: ["Diary", "Nuts", "Gluten", "Egg"],
  },
  {
    id: 7,
    image: "/Image/Paneer Tikka.jpg",
    name: "Panner Tikka Masala Combo",
    alias: "Panner Combo",
    price: 15,
    tags: ["Diary", "Nuts", "Gluten", "Egg"],
  },
  {
    id: 8,
    image: "/Image/Chole.jpg",
    name: "Chickpea Masala Combo",
    alias: "Chickpea Combo",
    price: 15,
    tags: ["Vegan", "Gluten", "Egg"],
  },
  {
    id: 9,
    image: "/Image/Tandoori.jpg",
    name: "Tandoori Chicken Combo",
    alias: "Tandoori Combo",
    price: 9,
    tags: ["Diary"],
  },
  {
    id: 10,
    image: "/Image/Samosa.jpg",
    name: "Samosa",
    alias: "Samosa",
    price: 5,
    tags: ["Vegan", "Gluten"],
  },
  {
    id: 11,
    image: "/Image/Lassi.jpg",
    name: "Mango Lassi",
    alias: "Mango Lassi",
    price: 5,
    comboPrice: 3,
    tags: ["Diary", "Cold"],
  },
  {
    id: 12,
    image: "/Image/Water.jpg",
    name: "Water",
    alias: "Water",
    price: 2,
    tags: ["Cold"],
  },
  {
    id: 13,
    image: "/Image/Soda.jpg",
    name: "Soda",
    alias: "Soda",
    price: 2,
    tags: ["Cold"],
  },
];

export default Food_List;
